language: node_js
node_js: '10'
cache: yarn
before_install: cp theme-config.yml themes/fing/_config.yml
before_install:
- openssl aes-256-cbc -K $encrypted_9c9c237d0267_key -iv $encrypted_9c9c237d0267_iv
  -in .travis.enc -out _config.yml -d
script: yarn deploy
after_failure: cat /home/travis/.npm/_logs/*-debug.log
branches:
  only:
  - master
os: osx
